/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/hcs/tech/board.vue')['default']
    Closed: typeof import('./src/components/hcs/flow/closed.vue')['default']
    Data1: typeof import('./src/components/data/data1.vue')['default']
    Data2: typeof import('./src/components/data/data2.vue')['default']
    Dbd: typeof import('./src/components/hcs/product/dbd.vue')['default']
    Done: typeof import('./src/components/hcs/flow/done.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    File: typeof import('./src/components/hcs/info/file.vue')['default']
    Graph: typeof import('./src/components/hcs/flow/graph.vue')['default']
    Job: typeof import('./src/components/hcs/process/job.vue')['default']
    List: typeof import('./src/components/hcs/blue/list.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    Right: typeof import('./src/components/hcs/sys/right.vue')['default']
    Role: typeof import('./src/components/hcs/sys/role.vue')['default']
    RoleRright: typeof import('./src/components/hcs/sys/roleRright.vue')['default']
    RoleUser: typeof import('./src/components/hcs/sys/roleUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./src/components/hcs/flow/send.vue')['default']
    State: typeof import('./src/components/hcs/product/state.vue')['default']
    Todo: typeof import('./src/components/hcs/flow/todo.vue')['default']
    User: typeof import('./src/components/hcs/sys/user.vue')['default']
    Web: typeof import('./src/components/Web.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
