/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/tech/board.vue')['default']
    ConstValue: typeof import('./src/components/sys/constValue.vue')['default']
    Done: typeof import('./src/components/approval/done.vue')['default']
    Draft: typeof import('./src/components/tech/draft.vue')['default']
    Draw: typeof import('./src/components/workflow/draw.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    File: typeof import('./src/components/info/file.vue')['default']
    Flow: typeof import('./src/components/workflow/flow.vue')['default']
    Instance: typeof import('./src/components/workflow/instance.vue')['default']
    List: typeof import('./src/components/bluePrint/list.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    Process: typeof import('./src/components/process/process.vue')['default']
    ProcessV: typeof import('./src/components/process/processV.vue')['default']
    Right: typeof import('./src/components/sys/right.vue')['default']
    Role: typeof import('./src/components/sys/role.vue')['default']
    RoleRright: typeof import('./src/components/sys/roleRright.vue')['default']
    RoleUser: typeof import('./src/components/sys/roleUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./src/components/approval/send.vue')['default']
    Solo: typeof import('./src/components/tech/solo.vue')['default']
    State: typeof import('./src/components/product/state.vue')['default']
    Step: typeof import('./src/components/tech/step.vue')['default']
    StepS01: typeof import('./src/components/process/steps/StepS01.vue')['default']
    StepS02: typeof import('./src/components/process/steps/StepS02.vue')['default']
    StepS03: typeof import('./src/components/process/steps/StepS03.vue')['default']
    StepS04: typeof import('./src/components/process/steps/StepS04.vue')['default']
    StepS05: typeof import('./src/components/process/steps/StepS05.vue')['default']
    StepS06: typeof import('./src/components/process/steps/StepS06.vue')['default']
    StepS07: typeof import('./src/components/process/steps/StepS07.vue')['default']
    StepS08: typeof import('./src/components/process/steps/StepS08.vue')['default']
    StepS09: typeof import('./src/components/process/steps/StepS09.vue')['default']
    StepS10: typeof import('./src/components/process/steps/StepS10.vue')['default']
    StepS11: typeof import('./src/components/process/steps/StepS11.vue')['default']
    StepS12: typeof import('./src/components/process/steps/StepS12.vue')['default']
    StepS13: typeof import('./src/components/process/steps/StepS13.vue')['default']
    StepS14: typeof import('./src/components/process/steps/StepS14.vue')['default']
    StepS15: typeof import('./src/components/process/steps/StepS15.vue')['default']
    StepS16: typeof import('./src/components/process/steps/StepS16.vue')['default']
    Task: typeof import('./src/components/process/task.vue')['default']
    Todo: typeof import('./src/components/approval/todo.vue')['default']
    Transfer: typeof import('./src/components/product/transfer.vue')['default']
    User: typeof import('./src/components/sys/user.vue')['default']
    Web: typeof import('./src/components/Web.vue')['default']
    Work: typeof import('./src/components/process/work.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
